version: '3.9'

services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: org_pedia
    ports:
      - "5432:5432"
  
  flask:
    build: .
    depends_on:
      - db
    environment:
      DATABASE_URL: "postgresql://postgres:yourpassword@db:5432/org_pedia"
    entrypoint: ["/bin/sh", "-c", "flask db upgrade && python app.py"]
    ports:
      - "8000:8000"
